version: '3'
services:
  api:
    build: .
    ports:
      - "8010:8010"
    volumes:
      - .:/app
    depends_on:
      - db
    container_name: klontong-app
  db:
    image: postgres:13
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: